---
first_model:
  name: mnasnet1_3
  weights_file:              #Optional. Use your own pth file or leave epty to use pretrained weights form PyTorch.
second_model:
  enable: true
  name: densenet121
  weights_file:              #Optional. Use your own pth file or leave epty to use pretrained weights form PyTorch.
  score_fn: entropy             #Options: [maxp, difference, entropy, oracle]
  threshold: 0.7798
  postcheck: true
memory:
  enable: false
  method: dhash              #Options: [dhash, invariants]
  duplicates: 0
  transforms: 0
dataset_path: "/media/mike/EXT4-480GB/Datasets/ImageNet-Custom/val_resized_10K/"
root_password:                #Optional
